# make file generated by gryphel build system

mk_COptions = -c -Wall -Wmissing-prototypes -Wno-uninitialized -Wundef -Wstrict-prototypes -mdynamic-no-pic -fpascal-strings -arch x86_64 -Os

.PHONY: TheDefaultOutput clean

TheDefaultOutput : minivmac.app/Contents/MacOS/minivmac

bld/MYOSGLUE.o : src/MYOSGLUE.c src/COMOSGLU.h src/STRCONST.h src/CONTROLM.h src/CNFGGLOB.h
	gcc "src/MYOSGLUE.c" -o "bld/MYOSGLUE.o" $(mk_COptions) -I/usr/local/include/ -D_GNU_SOURCE=1 -D_THREAD_SAFE
bld/GLOBGLUE.o : src/GLOBGLUE.c src/CNFGGLOB.h
	gcc "src/GLOBGLUE.c" -o "bld/GLOBGLUE.o" $(mk_COptions)
bld/M68KITAB.o : src/M68KITAB.c src/CNFGGLOB.h
	gcc "src/M68KITAB.c" -o "bld/M68KITAB.o" $(mk_COptions)
bld/MINEM68K.o : src/MINEM68K.c src/CNFGGLOB.h
	gcc "src/MINEM68K.c" -o "bld/MINEM68K.o" $(mk_COptions)
bld/VIAEMDEV.o : src/VIAEMDEV.c src/CNFGGLOB.h
	gcc "src/VIAEMDEV.c" -o "bld/VIAEMDEV.o" $(mk_COptions)
bld/IWMEMDEV.o : src/IWMEMDEV.c src/CNFGGLOB.h
	gcc "src/IWMEMDEV.c" -o "bld/IWMEMDEV.o" $(mk_COptions)
bld/SCCEMDEV.o : src/SCCEMDEV.c src/CNFGGLOB.h
	gcc "src/SCCEMDEV.c" -o "bld/SCCEMDEV.o" $(mk_COptions)
bld/RTCEMDEV.o : src/RTCEMDEV.c src/CNFGGLOB.h
	gcc "src/RTCEMDEV.c" -o "bld/RTCEMDEV.o" $(mk_COptions)
bld/ROMEMDEV.o : src/ROMEMDEV.c src/CNFGGLOB.h
	gcc "src/ROMEMDEV.c" -o "bld/ROMEMDEV.o" $(mk_COptions)
bld/SCSIEMDV.o : src/SCSIEMDV.c src/CNFGGLOB.h
	gcc "src/SCSIEMDV.c" -o "bld/SCSIEMDV.o" $(mk_COptions)
bld/SONYEMDV.o : src/SONYEMDV.c src/CNFGGLOB.h
	gcc "src/SONYEMDV.c" -o "bld/SONYEMDV.o" $(mk_COptions)
bld/SCRNEMDV.o : src/SCRNEMDV.c src/CNFGGLOB.h
	gcc "src/SCRNEMDV.c" -o "bld/SCRNEMDV.o" $(mk_COptions)
bld/KBRDEMDV.o : src/KBRDEMDV.c src/CNFGGLOB.h
	gcc "src/KBRDEMDV.c" -o "bld/KBRDEMDV.o" $(mk_COptions)
bld/SNDEMDEV.o : src/SNDEMDEV.c src/CNFGGLOB.h
	gcc "src/SNDEMDEV.c" -o "bld/SNDEMDEV.o" $(mk_COptions)
bld/MOUSEMDV.o : src/MOUSEMDV.c src/CNFGGLOB.h
	gcc "src/MOUSEMDV.c" -o "bld/MOUSEMDV.o" $(mk_COptions)
bld/PROGMAIN.o : src/PROGMAIN.c src/CNFGGLOB.h
	gcc "src/PROGMAIN.c" -o "bld/PROGMAIN.o" $(mk_COptions)

ObjFiles = \
	bld/MINEM68K.o \
	bld/MYOSGLUE.o \
	bld/GLOBGLUE.o \
	bld/M68KITAB.o \
	bld/VIAEMDEV.o \
	bld/IWMEMDEV.o \
	bld/SCCEMDEV.o \
	bld/RTCEMDEV.o \
	bld/ROMEMDEV.o \
	bld/SCSIEMDV.o \
	bld/SONYEMDV.o \
	bld/SCRNEMDV.o \
	bld/KBRDEMDV.o \
	bld/SNDEMDEV.o \
	bld/MOUSEMDV.o \
	bld/PROGMAIN.o \


minivmac.app/Contents/Resources/AppIcon.icns : src/AppIcon.icns
	rm -fr "minivmac.app/"
	rm -fr "AppTemp/"
	mkdir "AppTemp/"
	mkdir "AppTemp/Contents/"
	mkdir "AppTemp/Contents/MacOS/"
	mkdir "AppTemp/Contents/Resources/"
	mkdir "AppTemp/Contents/Resources/English.lproj/"
	cp "src/AppIcon.icns" "AppTemp/Contents/Resources/"
	cp "src/Info.plist" "AppTemp/Contents/"
	printf "dummy\n" > "AppTemp/Contents/Resources/English.lproj/dummy.txt"
	printf "APPL????" > "AppTemp/Contents/PkgInfo"
	mv "AppTemp/" "minivmac.app/"

minivmac.app/Contents/MacOS/minivmac : $(ObjFiles) minivmac.app/Contents/Resources/AppIcon.icns
	gcc \
		-o "minivmac.app/Contents/MacOS/minivmac" \
		$(ObjFiles) -L/usr/local/lib -lSDLmain -lSDL -Wl,-framework,Cocoa -arch x86_64
	strip -u -r "minivmac.app/Contents/MacOS/minivmac"

clean :
	rm -f $(ObjFiles)
	rm -fr "minivmac.app/"
